%% Plot a network with spatial node positions.
%
% Visualizes a directed network graph with nodes positioned in 2D space.
% Sensors are shown as squares, extenders as triangles.
%
% Parameters:
% - G - `digraph` instance generated by `createSpatialNetwork`.
% - maxLength - Maximum coordinate value for axis limits.
%
function plotNetwork(G, maxLength)
    figure;
    hold on;
    axis equal;
    grid on;

    p = plot(G, 'MarkerSize', 8);
    p.XData = G.Nodes.xCoordinates;
    p.YData = G.Nodes.yCoordinates;
    p.NodeCData = G.Nodes.isSensor;

    markers = repmat("^", G.numnodes, 1);
    markers(G.Nodes.isSensor) = "square";
    p.Marker = markers;

    title('Network Topology');
    xlabel('X Position');
    ylabel('Y Position');
    xlim([0, maxLength]);
    ylim([0, maxLength]);

    hold off;
end
